### ISSUE TITLE
Feture request: add filename to FileOrStdin

### ISSUE THREAD

**Issue by adamflott** [thepacketgeek/clap-stdin#2]
I'd like to have the filename (or '-') available in `FileOrStdin` for improving my error messages. Is that possible to add?

And while I'm here:
* doc syntax error: https://github.com/thepacketgeek/clap-stdin/blob/main/src/file_or_stdin.rs#L34
* typo? "can wrap any time" => "can wrap any type" (a few instances of this)

Thanks for the great crate!

**Comment by adamflott** [comment]
I use https://crates.io/crates/ariadne to make better error messages and part of that can include the filename

**Comment by thepacketgeek** [comment]
I'm working on a change that adds `io::Read` to `FileOrStdin` to avoid always forcing the input to be read to a String. Part of that work means saving the source of the input, so I should be able to expose the source with that. Let me see what I can do in the next week or so (Y)

**Comment by RGBCube** [comment]
There doesn't seem to be a way to access this anymore?

**Comment by thepacketgeek** [comment]
Sorry @RGBCube and @adamflott , I make `Source` private in 0.5.0 in case its impl changes. I just added back a `FileOrStdin::filename` to allow access to that value again. 

Will release in 0.5.1, please let me know if this usage still fits your needs

**Comment by RGBCube** [comment]
> Sorry @RGBCube and @adamflott , I make `Source` private in 0.5.0 in case its impl changes. I just added back a `FileOrStdin::filename` to allow access to that value again. 
> 
> Will release in 0.5.1, please let me know if this usage still fits your needs

No problem, happens to the best of us.

Thanks for the fix, that change was exactly what I was thinking about.
