### ISSUE TITLE
Reading from stdin without `-` using default value leads to hanging prompt

### ISSUE THREAD

**Issue by uncenter** [thepacketgeek/clap-stdin#7]
The [Reading from Stdin without special characters](https://github.com/thepacketgeek/clap-stdin#reading-from-stdin-without-special-characters) tip using default values with clap is great when input is provided from stdin (`echo "Hello, world!" | cargo run`) though when nothing is provided - `cargo run` - the program basically freezes.

![Screenshot 2024-04-24 at 10 47 35 (Code)](https://github.com/thepacketgeek/clap-stdin/assets/47499684/9b456ae5-cad8-43fe-b279-937050181b37)

My fear is that this might not be something you can even fix or detect! If so, sorry for this dumb question xD

**Comment by thepacketgeek** [comment]
In this case when the program is reading from stdin (since it wasn't piped in), you'll need to press ctrl+d to send EOF.

This is a good point that can cause confusion though, I'll see if it's possible to detect and log some instruction for that

**Comment by havenwood** [comment]
I agree piping and a program seeming to hang can be confusing, but since it's standard shell command behavior it seems nice to not print instructions by default. Maybe instructions could be an opt in option if added? Or if they're default, I'd appreciate an opt out option. 🙂

**Comment by thepacketgeek** [comment]
> since it's standard shell command behavior it seems nice to not print instructions by default
@havenwood Agreed!

@uncenter I believe the best way to address this is to add notes to the CLI help strings and/or docs?

E.g. something along these lines
```
struct Args {
    ...
    /// Read from a value or stdin. If no value or stdin is provided, will block on stdin until EOF is received (ctrl+d)
   input: MaybeStdin<String>,
   ...
}
```

**Comment by uncenter** [comment]
Fair enough! Thanks for looking into it.
